### PR TITLE
Update assets to jQuery-File-Upload 9.8.0

### PR DESCRIPTION
**Pull request by opti**
This PR includes:

* updated assets from jQuery-File-Upload [v9.8.0](https://github.com/blueimp/jQuery-File-Upload/releases/tag/9.8.0)
* moved `vendor/assets` to `app/assets` for Rails 4 compatibility
* couple more helpers for easy include `basic-plus`, `angularjs` or `jquery-ui` versions
* updated README.md

### CODE REVIEW

**Comment by ipd** [comment]
@opti ok, thanks for getting back to me.

**Comment by tors** [comment]
@opti Hola! Thanks for this! I've been very busy at work. I've added you as a collaborator.

**Comment by ipd** [comment]
Thanks @tors !

We should probably version the gem so that people who are on rails < 4.x will be able to continue to use the old version.

**Comment by opti** [comment]
Thanks for merging this @tors

**Comment by opti** [comment]
hey @tors I've created a release tag v0.4.2, if you don't mind you can push it to rubygems

**Comment by tors** [comment]
@opti roger that! Thanks!

**Comment by felixbuenemann** [comment]
You should probably add back the X-Requested-WIth Patch for the Iframe-Transport Middleware before making a new release, see commit d246fe6 for details.

**Comment by opti** [comment]
@felixbuenemann I'm not sure that this is a good idea to make those changes in that repo. This js file is copied from original repo. Making fixes here forces repo maintainers to always keep in mind this fix on every future assets upgrade.
Maybe it make sense to open a pull request with this fix to the @blueimp's original [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload) repo.

**Comment by felixbuenemann** [comment]
Jepp, that's what I though and it was rejected, see blueimp/jQuery-File-Upload#3291. The problem is that this repo used to have this patch, so not having it brakes the usage of the iframe transport middleware.

Maybe the middleware could be changed to somehow detect the request without the extra header.

**Comment by opti** [comment]
@felixbuenemann I see. You're feel free to add it back while there is no another solution yet.

**Comment by felixbuenemann** [comment]
I think the best solution is to remove the middleware, see #69 for reasons.

**Pull request merged**
