### PR TITLE
README, reference to an example app that supports resumable uploads

### PR DESCRIPTION
**Pull request by vgantchev**

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Please squash to a single commit.

**Comment by vgantchev** [comment]
Done!

**Comment by felixbuenemann** [comment]
Thanks, could you remove the commit "Bump v0.4.6" from your branch? It should already be on master. Maybe you branched from an older HEAD.

**Comment by vgantchev** [comment]
Would be faster to do a new PR at this point..

**Pull request closed without merging**
